from rosalind_utils import read_input

def lexv(s: str, n: int):
    #Generate all possible strings of length n from the alphabet in s
    #Thinking of a depth-first traversal
    #similar to lexf problem but want to include all possible lengths from 1 to n
    s = "".join(s)
    #base case: if n is 0, return a list with an empty string
    if n == 0: 
        return [""]
    results = []
    #append each character in s to the front of each string generated by a recursive call to lexv with n-1
    for c in s:
        results.append(c)
        if n > 1:
            for suffix in lexv(s, n-1):
                results.append(c + suffix)
    return results

data = read_input("data/rosalind_lexv.txt").split('\n')
s = data[0].split()
n = int(data[1])
results = lexv(s, n)
with open('output/lexv_output.txt', 'w') as f:
    f.write("\n".join(results))

