from rosalind_utils import read_input
from collections import deque

def reversal(perm):
    #generates all possible reversals of a permutation by reversing any subarray 
    #from idx i to j and keeping the rest of the permutation intact
    reversals = []
    n = len(perm)
    for i in range(n):
        for j in range(i+1, n):
            #reverses the subarray from i to j and append the new permutation
            new_perm = perm[:i] + perm[i:j+1][::-1] + perm[j+1:]
            reversals.append(new_perm)
    return reversals

def rear(pi, sigma):
    #BFS approach to find the minimum number of reversals to transform pi into sigma
    start = tuple(pi)
    target = tuple(sigma)

    if start == target:
        return 0
    
    #initialize the queue for BFS with the starting permutation and distance 0
    queue = deque([(start, 0)])
    visited = {start}

    while queue:
        current, dist = queue.popleft()
        for neighbor in reversal(current):
        #check each neighbor generated by reversal
            neighbor = tuple(neighbor)
            if neighbor == target:
            #if the neighbor is the target permutation, return the distance incremented by 1
                return dist + 1
            #if the neighbor has not been visited, add it to the queue with incremented distance
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append((neighbor, dist + 1))
    #if the target permutation is not reachable, return -1
    return -1

if __name__ == "__main__":
    data = read_input("data/rosalind_rear.txt").strip().split('\n')
    results = []
    i = 0
    while i < len(data):
        if data[i].strip():
            pi = list(map(int, data[i].split()))
            sigma = list(map(int, data[i+1].split()))
            results.append(rear(pi, sigma))
            i += 2
        else:
            i += 1
    print(' '.join(map(str, results)))